### ISSUE TITLE
False positive aleeas.com

### ISSUE THREAD

**Issue by ph00lt0** [unkn0w/disposable-email-domain-list#1]
aleeas.com is not a disposable email but is part of SimpleLogin which is used for security not for temporary emails.

**Comment by unkn0w** [comment]
Fixed - I've removed it from the list. Thx  👍

**Comment by rafaellop** [comment]
Add `podam.pl` which is an alternative to `niepodam.pl`

**Comment by domainfun** [comment]
> Fixed - I've removed it from the list. Thx 👍

@unkn0w Did you forget to push your change?

Both [domains.json](https://github.com/unkn0w/disposable-email-domain-list/blob/main/domains.json) and [domains.txt](https://github.com/unkn0w/disposable-email-domain-list/blob/main/domains.txt) on branch `main` still contain the domain name `aleeas.com`.
