### ISSUE TITLE
Remove non disposable

### ISSUE THREAD

**Issue by ghost** [unkn0w/disposable-email-domain-list#12]
Hi!

I found `aleeas.com` in your blacklist.

### aleeas.com is NOT disposable email domain

It is owned by SimpleLogin (you can check this simply through mx, which will point to SimpleLogin) service which is NOT disposable email provider.

They even have article about why they are NOT disposable email provider:
https://simplelogin.io/docs/why-simplelogin-is-not-disposable-mail/

If you still think that this is disposable domain, I ask you to look on this (and follow links, please):

What will you say about such websites:

[One (link)](https://smailpro.com/advanced)
[Two (link)](https://tempmail.dev/en/Gmail)
[Three (link)](https://www.emailnator.com/)
All three websites provides DISPOSABLE gmail addresses.

So block gmail.

Also. Apple provides DISPOSABLE solutions too.

[Proof one](https://www.idownloadblog.com/2021/09/21/apple-hide-my-email-icloud-website/) and [proof two](https://support.apple.com/guide/icloud/stop-using-or-reactivate-addresses-mm3adb030cbf/icloud) (official manual)

So block ICloud.

Also. Outlook provides DISPOSABLE addresses. [Proof](https://support.microsoft.com/en-us/office/add-or-remove-an-email-alias-in-outlook-com-459b1989-356d-40fa-a689-8f285b13f1f2). You can create and delete three ones per day.

So  block Outlook.

Do you think it is end? Hell no!

Yahoo provides DISPOSABLE mails. [Proof](https://help.yahoo.com/kb/SLN28815.html)

So block Yahoo.

### IT IS CRITICAL FOR UNDERSTANDING TO FOLLOW ALL OFFICIAL LINKS IN THIS POST TO GET PROOFS.

Now it is looking like discrimination of people who are using privacy oriented services, with the _**SAME**_ functionality as proprietary and popular ones.

So I ask you to _**UNBLOCK**_ `aleeas.com`

If not, please block:
```
gmail.com
outlook.com
icloud.com
yahoo.com
```

**Comment by Nikola-Test-for-Proton** [comment]
Hi, 

Just adding to this issue, I work for Proton (as well as SimpleLogin's) Anti-Abuse team. 

Like OP mentioned above, the email addresses or aliases that one can create with the domains we offer are not disposable, but rather permanent. We also consider anti-spam to be of the utmost importance and have mechanisms in place to prevent different sorts of abuse on our service as well as off-platform. 

We would appreciate it if you could look into this for us and to remove the aleeas.com from your list accordingly.

Have a pleasant day and happy holidays!

Best regards,

**Comment by domainfun** [comment]
@Nikola-Test-for-Proton 

> We would appreciate it if you could look into this for us and to remove the aleeas.com from your list accordingly.

Just in case you didn't see [ticket #1](https://github.com/unkn0w/disposable-email-domain-list/issues/1), where I have added [a comment](https://github.com/unkn0w/disposable-email-domain-list/issues/1#issuecomment-1877050830) for the repository owner @unkn0w ("Did you forget to push your change?").

By the way, It looks like "Hvihifycihuf" created a temporary GitHub account just for reporting this [issue #12](https://github.com/unkn0w/disposable-email-domain-list/issues/12), and then deleted their user account?  In my opinion this is not a great idea for collaborating on a repository someone has published in their own (unpaid) time, see user [ghost](https://github.com/ghost).

**Comment by unkn0w** [comment]
Done - **aleeas.com** is now removed from the list.
Probably it was added again accidentally - sorry for that.
